image: python:3.5-jessie

stages:
  - sonar

sonar:
  stage: sonar
  before_script:
  - apt-get --yes -qq update && apt-get --yes -qq install zip apache2-dev
  # Installs sonar-runner ZIP file
  - if [[ ! -d sonar-scanner-3.0.3.778-linux ]]; then
  -     wget --no-verbose https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip
  -     unzip -q sonar-scanner-cli-3.0.3.778-linux.zip
  - fi
  - sonar-scanner-3.0.3.778-linux/bin/sonar-scanner --version
  # Installs pip requirements
  - test ! -d .pip && mkdir .pip
  - pip install --cache-dir .pip/ pylint pylint-django
  - if [[ -f requirements/common.txt ]] && [[ -f requirements/constraints.txt ]]; then
  -     pip install --cache-dir .pip/ --requirement requirements/common.txt --constraint requirements/constraints.txt;
  - fi
  script:
  # Runs the sonar-runner
  - export SONAR_SCANNER_OPTS="-Xmx512m"
  - export SONAR_USER_HOME=.
  - sonar-scanner-3.0.3.778-linux/bin/sonar-scanner -Dsonar.host.url="http://ulysse.ville.tg:9000"
  cache:
    paths:
    - sonar-scanner-3.0.3.778-linux/
    - .pip/
    - .scannerwork/
  tags:
  - sonar
