---
# Gitlab tasks for the intranet application
image: python:3.7-buster

stages:
  - lint
  - deploy

variables:
  DEBUG_SONAR: 0
  DEBUG_FLAKE8: 0

# Checks python code against flake8
flake8:
  stage: lint
  before_script:
    - pip --cache-dir .pip/ install flake8
  script:
    - "[[ ${DEBUG_FLAKE8} -eq 1 ]] && ls -la"
    - flake8 ./buttons
  tags:
    - python3.7
    - docker

release_staging:
  stage: deploy
  needs: [ flake8 ]
  before_script:
    - pip --cache-dir .pip/ install -r requirements/deploy.txt
  script: |
    python3 setup.py sdist bdist_wheel
    python3 -m twine upload \
      --repository-url https://test.pypi.org/legacy/ \
      --username "$USERNAME_STAGING" \
      --password "$PASSWORD_STAGING" \
      --skip-existing \
      dist/*
  cache:
    paths:
      - .pip/
  tags:
    - python3.7
    - docker

release:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG != null
  needs: [ flake8 ]
  before_script:
    - pip --cache-dir .pip/ install -r requirements/deploy.txt
  script: |
    python3 setup.py sdist bdist_wheel
    python3 -m twine upload \
      --username "$USERNAME" \
      --password "$PASSWORD" \
      --skip-existing \
      dist/*
  cache:
    paths:
      - .pip/
  tags:
    - python3.7
    - docker
